remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# more info https://github.com/pages-themes/minimal

title: Tutorials by Janna Avon
description: This site collects and shares instructional guides developed to support teaching.
email: avonj@lafayette.edu
